# Generated by Django 4.2.23 on 2025-08-22 17:20

from django.db import migrations, models
import django.db.models.deletion
import trips.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100)),
                ("apellido", models.CharField(blank=True, max_length=100)),
                ("domicilio", models.CharField(blank=True, max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "dni",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "gmail",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "cuit",
                    models.CharField(blank=True, max_length=11, null=True, unique=True),
                ),
                (
                    "tipo_iva",
                    models.CharField(
                        choices=[
                            ("RI", "Responsable Inscripto"),
                            ("MT", "Monotributista"),
                            ("CF", "Consumidor Final"),
                            ("EX", "Exento"),
                            ("NR", "No Responsable"),
                        ],
                        default="CF",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("surname", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "dni",
                    models.CharField(
                        blank=True,
                        help_text="DNI del conductor",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "gmail",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Número de licencia del conductor",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento de licencia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("punto_venta", models.PositiveIntegerField(default=1)),
                ("tipo_cbte", models.PositiveIntegerField(default=6)),
                ("cae", models.CharField(blank=True, max_length=14, null=True)),
                ("cae_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="trips.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "price_per_kilo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio por kilo"
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Volumen (m³)"
                    ),
                ),
                (
                    "trailer_category",
                    models.CharField(
                        choices=[
                            ("flatbed", "Remolque de plataforma (Flatbed)"),
                            ("dry_van", "Remolque cerrado (Dry Van)"),
                            ("reefer", "Remolque refrigerado (Reefer)"),
                            ("tanker", "Remolque cisterna (Tanker)"),
                            ("tautliner", "Remolque de lona (Tautliner)"),
                            ("chassis", "Remolque portacontenedores (Chassis)"),
                            ("lowboy", "Remolque Lowboy (Cama baja)"),
                            ("hopper", "Remolque tolva (Hopper)"),
                            ("livestock", "Remolque jaula (Livestock trailer)"),
                            ("car_carrier", "Remolque de automóviles (Car carrier)"),
                            ("dump_trailer", "Remolque basculante (Dump trailer)"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de remolque necesario",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trailer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[trips.models.validate_plate],
                        verbose_name="Licencia",
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(verbose_name="Vencimiento de licencia"),
                ),
                (
                    "technical_id",
                    models.CharField(max_length=100, verbose_name="Técnica"),
                ),
                (
                    "technical_expiry",
                    models.DateField(verbose_name="Vencimiento de técnica"),
                ),
                (
                    "cargo_type",
                    models.CharField(max_length=100, verbose_name="Tipo de carga"),
                ),
                (
                    "homologation",
                    models.BooleanField(default=False, verbose_name="Homologación"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_address", models.CharField(max_length=255)),
                ("end_address", models.CharField(max_length=255)),
                (
                    "total_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor del viaje"
                    ),
                ),
                (
                    "received_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kilos recibidos",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("recibido", "Recibido"),
                            ("facturado", "Facturado"),
                            ("no_completado", "No completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("departure_date", models.DateTimeField(blank=True, null=True)),
                ("arrival_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="trips.client"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="trips.driver"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trips.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[trips.models.validate_plate],
                        verbose_name="Patente",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="vehicles/"),
                ),
                (
                    "price_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio por kilómetro del vehículo",
                        max_digits=10,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trips.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trips.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("nota_credito", "Nota de crédito"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                            ("efectivo", "Efectivo"),
                            ("cheque", "Cheque"),
                            ("retencion", "Retención"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                ("factura_emitida", models.BooleanField(default=False)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="trips.invoice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="trips",
            field=models.ManyToManyField(
                blank=True, related_name="invoices", to="trips.trip"
            ),
        ),
        migrations.CreateModel(
            name="DriverAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("peaje", "Peaje"),
                            ("combustible", "Combustible"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="trips.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                (
                    "locality",
                    models.CharField(max_length=100, verbose_name="Localidad"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Código Postal"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="trips.driver",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("fixed", models.BooleanField(default=False)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_errors",
                        to="trips.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asesoramiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("asesoramiento", models.TextField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asesoramientos",
                        to="trips.client",
                    ),
                ),
            ],
        ),
    ]
