# Generated by Django 5.2.1 on 2025-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CPEAutomotor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nro_ctg",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número CTG"
                    ),
                ),
                (
                    "tipo_carta_porte",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Tipo de carta de porte",
                    ),
                ),
                ("sucursal", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "nro_orden",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Número de orden",
                    ),
                ),
                ("estado", models.CharField(blank=True, max_length=10, null=True)),
                ("fecha_emision", models.DateTimeField(blank=True, null=True)),
                ("fecha_inicio_estado", models.DateTimeField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("raw_response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CPE Automotor",
                "verbose_name_plural": "CPE Automotores",
            },
        ),
    ]
